CREATE TABLE IF NOT EXISTS customer (
  id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL, name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL, status VARCHAR(16) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(), deleted_at TIMESTAMP
);
CREATE TABLE IF NOT EXISTS product (
  id BIGINT PRIMARY KEY, sku VARCHAR(40) NOT NULL, name VARCHAR(120) NOT NULL,
  category VARCHAR(40) NOT NULL, price NUMERIC(12, 2) NOT NULL
);
CREATE TABLE IF NOT EXISTS currency (code VARCHAR(3) PRIMARY KEY, rate NUMERIC(12, 6) NOT NULL);
CREATE TABLE IF NOT EXISTS purchase_order (
  id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL, customer_id BIGINT NOT NULL,
  status VARCHAR(16) NOT NULL, total NUMERIC(12, 2) NOT NULL, currency_code VARCHAR(3) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(), deleted_at TIMESTAMP
);
CREATE TABLE IF NOT EXISTS order_item (
  id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL, order_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL, quantity INT NOT NULL, price NUMERIC(12, 2) NOT NULL
);
CREATE TABLE IF NOT EXISTS invoice (
  id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL, order_id BIGINT NOT NULL,
  number VARCHAR(32) NOT NULL, status VARCHAR(16) NOT NULL, amount NUMERIC(12, 2) NOT NULL,
  issued_at TIMESTAMP NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS payment (
  id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL, invoice_id BIGINT NOT NULL,
  amount NUMERIC(12, 2) NOT NULL, method VARCHAR(16) NOT NULL,
  paid_at TIMESTAMP NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT PRIMARY KEY, tenant_id BIGINT, actor VARCHAR(80) NOT NULL, action VARCHAR(40) NOT NULL,
  entity VARCHAR(40) NOT NULL, entity_id BIGINT NOT NULL, at TIMESTAMP NOT NULL DEFAULT now()
);
CREATE SEQUENCE IF NOT EXISTS customer_seq START WITH 1000 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS audit_log_seq START WITH 1000 INCREMENT BY 50;
