version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    groups:
      maven-plugins:
        patterns: ["org.apache.maven.plugins:*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
