spring.datasource.url=jdbc:postgresql://localhost:5432/billing
spring.datasource.username=billing
spring.datasource.password=billing
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
